### ISSUE TITLE
Compatibility problem with Lanolin

### ISSUE THREAD

**Issue by TimGoll** [asiekierka/TinkeredHegemony#10]
You can find the details [here](https://github.com/SirLyle/Lanolin/issues/3).

**Comment by asiekierka** [comment]
From the issue: The first and third problem pertain to Tinkered Hegemony and are fixed in 0.2.1. The second problem is a feature that has to be implemented in Lanolin.

**Comment by TimGoll** [comment]
Thanks @asiekierka 
@SirLyle maybe this is a helpful information for you
