### ISSUE TITLE
[Suggestion] Have tools use wooden handles

### ISSUE THREAD

**Issue by YaibaToKen** [asiekierka/TinkeredHegemony#3]
In order to provide more similar tools to vanilla ones, I recommend replacing the handles with wooden ones.

**Comment by asiekierka** [comment]
You can use any handle, it's just the JEI preview which doesn't take that into account.

**Comment by YaibaToKen** [comment]
Ohh apologies then, I had no idea. Does that mean the only material taken into account is the head part? Also, for those tools that have two head parts (I think the mattock is the only one) does it check for both?

**Comment by asiekierka** [comment]
Yes. For two head parts, I'm not sure if it requires both or at least one to match the material; I don't remember offhand, please check! (I think it requires both)
