### ISSUE TITLE
[Question] Recipe Replacement

### ISSUE THREAD

**Issue by NillerMedDild** [asiekierka/TinkeredHegemony#5]
Hey!

I've noticed that the replacement of normal tools with Tinkers' tools works for both Immersive Engineering and Hooked, but not Ancient Warfare 2 - Do the recipes need to be registered in a certain way, or just not in `PostInit`?

**Comment by asiekierka** [comment]
First, there's a difference between "visible in JEI" and "working".

For JEi visibility, you *should* be registering in the RegistryEvent.Register<IRecipe> event if possible. If you can't do that, then the relevant postInit *must* run before Tinkered Hegemony's postInit.

For functioning (without JEI reflecting the changes), it should work regardless. Did you try in a crafting table?

**Comment by NillerMedDild** [comment]
The recipe works, it's just disabled incorrectly in JEI, thank you :)
